FROM kavolorn/opencv

MAINTAINER Lewis Brown <github.com/ramity>

RUN apt-get update -y
RUN apt-get install -y libgtk2.0-dev pkg-config

WORKDIR /project

ENTRYPOINT ["tail", "-f", "/dev/null"]
